# Setup
title:               '연재씌'
tagline:             '2021.02'
description:         '전남대학교 수학과 3학년'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              정연재
  url:               'https://github.com/YeonjaeMan/yeonjaeman.github.io'
  email:             jgg9809@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
